### ISSUE TITLE
Crash when i try to open it

### ISSUE THREAD

**Issue by gumziler** [marco-calautti/SigpatchesModuleWiiU#8]
It just give's me a crash when i try to run it, i tried tiramisu and aroma, both gave me the same result

**Comment by marco-calautti** [comment]
How are you "running" this file? You are supposed to copy it inside the aroma folder on your sdcard so that Aroma can load it up on boot. This file is not supposed to be executed by other means (e.g., using the Homebrew Launcher).

**Comment by marco-calautti** [comment]
Refer to this guide on how to use the sigpatches: https://wiiu.hacks.guide/
